project:
  type: website


website:
  title: "ABACBS workshop 2023 - SPIAT & spaSim"
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        file: index.qmd
      - Setup.qmd
      - Workshop_materials.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
