project:
  type: website


website:
  title: "ABACBS workshop 2023 - SPIAT & spaSim"
  navbar:
    background: primary
    search: true
    left:
      - href: ABACBS_workshop_SPIAT_spaSim.qmd
        text: Home
      - Setup.qmd
      - Workshop_materials.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
