project:
  type: website


website:
  title: "ABACBS workshop 2023 - SPIAT & spaSim"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - docs/Setup.qmd
      - docs/Workshop_materials.qmd


format:
  html:
    theme: cosmo
    toc: true
