project:
  type: website


website:
  title: "ABACBS workshop 2023 - SPIAT & spaSim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: docs/Setup.qmd
        text: Setup
      - href: docs/Workshop_materials.qmd
        text: Workshop materials


format:
  html:
    theme: cosmo
    css: style.css
    toc: true
